### ISSUE TITLE
Clean main directory

### ISSUE THREAD

**Issue by xvilo** [janvankampen/heldnodig-site#28]
The main directory is getting crowded as it serves multiple types of files
What should be done:

- Move assets (images, styles etc) to sub directories
    - https://github.com/janvankampen/heldnodig-site/pull/29/files
- Move all other publicly served files to a `public/` folder and use this as docroot. (Is this possible @ferrydeboer / @janvankampen?)

**Comment by ferrydeboer** [comment]
I agree on cleaning this up. I was also not a big fan of the Docker files residing in what's essentially the application root. I would personally like the app root to a src dir and add the Docker setup on that same level as well.
